language: node_js
node_js:
  - 12
  - 10
  - 8

addons:
  apt:
    packages:
    - libgconf-2-4

script:
  # Run tests without coverage since it's 2x faster
  - npm run test:jest -- --runInBand

# Trigger a push build on master branches only + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master

stages:
  - lint
  - test
  - typecheck
  - integration
  - coverage
  - name: release
    if: type != pull_request AND branch = master
  - name: documentation
    if: type != pull_request AND branch = master
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
        - npx danger ci

    - stage: typecheck
      script:
        - npm run flow check

    - stage: integration
      script:
        # Compile JS
        - npm run compile
        # Build all examples
        - npm run build:basic
        - npm run build:customised
        - npm run build:sections
        # Check that examples really works: no JS errors on load
        - npm run test:browser:pre
        - npm run test:browser:basic
        - npm run test:browser:customised
        - npm run test:browser:sections
        # Run integration tests with Cypress
        - npm run test:cypress:pre
        - npm run test:cypress:startServer &
        - npm run test:cypress:startServer:post
        - npm run test:cypress:run

    - stage: coverage
      script:
        # Run tests with coverage
        - npm run test:coverage -- --runInBand
        # Upload coverage report to Codecov
        - bash <(curl -s https://codecov.io/bash)

    - stage: release
      script:
        - npm install --no-save semantic-release-tamia
        - >-
          npx semantic-release --analyze-commits semantic-release-tamia/analyzeCommits --verify-release semantic-release-tamia/verifyRelease --generate-notes semantic-release-tamia/generateNotes

    - stage: documentation
      script:
        # Trigger https://react-styleguidist.js.org build on Netlify
        - curl -X POST -d '{}' https://api.netlify.com/build_hooks/591308eba700c425fc1e8a54
