language: node_js
node_js:
  - 4
  - 6
  - 7
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - travis_phantomjs
env:
  # Test everything in Webpack 1 and 2
  - export WEBPACK_VERSION="2"
  - export WEBPACK_VERSION="1"
before_install:
  # Upgrade PhantomJS
  - |
      export PHANTOMJS_VERSION=2.1.1
      export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH
      if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then
        rm -rf $PWD/travis_phantomjs
        mkdir -p $PWD/travis_phantomjs
        wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
        tar -xvf phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs
      fi
      phantomjs -v
before_script:
  # Manually install Webpack 1 or 2
  - if [ "$WEBPACK_VERSION" == "1" ]; then yarn add webpack@1; fi
  - yarn list webpack
script:
  # Run tests
  - |
    yarn run lint
    echo "TRAVIS_NODE_VERSION=$TRAVIS_NODE_VERSION"
    if [[ "$TRAVIS_NODE_VERSION" =~ ^(4|5)$ ]]; then
      NODE_ENV=test node --harmony-proxies $(npm bin)/jest --runInBand
    else
      if [[ "$TRAVIS_NODE_VERSION" == "7" && "$WEBPACK_VERSION" == "2"  ]]; then
        yarn run test:coverage -- --runInBand
      else
        yarn run test:jest -- --runInBand
      fi
    fi
  # Build all examples
  - yarn run build
  - yarn run build:customised
  - yarn run build:sections
  # Check that examples really works: no JS errors on load
  - yarn run phantomjs
  - yarn run phantomjs:customised
  - yarn run phantomjs:sections
after_success:
  - |
    if [[ "$TRAVIS_NODE_VERSION" == "7" && "$WEBPACK_VERSION" == "2"  ]]; then
      # Make release with semantic-release if needed
      npm run semantic-release
      # Upload coverage report to Codecov
      bash <(curl -s https://codecov.io/bash)
    fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
