language: node_js
node_js:
  - 4
  - 6
  - 8
  - 9
matrix:
  allow_failures:
    - node_js: 4
cache:
  directories:
    - node_modules
before_install:
  # Upgrade npm
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@latest; fi
script:
  # Run lint
  - npm run lint
  # Run tests and Danger.js
  - |
    if [[ "$TRAVIS_NODE_VERSION" == "4" ]]; then
      NODE_ENV=test node --harmony-proxies $(npm bin)/jest --runInBand
    else
      if [[ "$TRAVIS_NODE_VERSION" == "9" ]]; then
        npx danger ci
        npm run test:coverage -- --runInBand
      else
        npm run test:jest -- --runInBand
      fi
    fi
  # Compile code
  - npm run compile
  # Build all examples
  - npm run build
  - npm run build:customised
  - npm run build:sections
  - |
    if [[ "$TRAVIS_NODE_VERSION" == "8" ]]; then
      # Check that examples really works: no JS errors on load
      npm run test:browser:pre
      npm run test:browser
      npm run test:browser:customised
      npm run test:browser:sections
      # Run integration tests with cypress
      npm run test:cypress:pre
      npm run test:cypress:startServer &
      npm run test:cypress:startServer:post
      npm run test:cypress:run
    fi
after_success:
  # Make release with semantic-release if needed
  - npm install -g semantic-release travis-deploy-once
  - npm install --no-save semantic-release-tamia
  - travis-deploy-once "semantic-release --analyze-commits semantic-release-tamia/analyzeCommits --verify-release semantic-release-tamia/verifyRelease --generate-notes semantic-release-tamia/generateNotes"
  - |
    if [[ "$TRAVIS_NODE_VERSION" == "9" ]]; then
      # Upload coverage report to Codecov
      bash <(curl -s https://codecov.io/bash)
      # Update site
      if [[ "$TRAVIS_BRANCH" == "master" ]]; then
        curl -X POST -d '{}' https://api.netlify.com/build_hooks/591308eba700c425fc1e8a54
      fi
    fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
