language: node_js
node_js:
  - 9
  - 8
  - 6
env:
  - WEBPACK_VERSION= # Current, from package.json
install:
  # Use npm 5.7.x since it has introduced `npm ci`
  - if [[ `npm -v` != 5.7* ]]; then npm install -g npm@'>=5.7.1'; fi
  - npm ci
before_script:
  # Install Webpack version
  - if [[ -n "$WEBPACK_VERSION" ]]; then npm install --no-save webpack@$WEBPACK_VERSION; fi
script:
  # Run tests without coverage since it's 2x faster
  - npm run test:jest -- --runInBand
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
stages:
  - lint
  - test
  - integration
  - coverage
  - release
  - name: documentation
    if: branch = master
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
        - npx danger ci

    - stage: integration
      script:
        # Compile JS
        - npm run compile
        # Build all examples
        - npm run build:basic
        - npm run build:customised
        - npm run build:sections
        # Check that examples really works: no JS errors on load
        - npm run test:browser:pre
        - npm run test:browser:basic
        - npm run test:browser:customised
        - npm run test:browser:sections
        # Run integration tests with Cypress
        - npm run test:cypress:pre
        - npm run test:cypress:startServer &
        - npm run test:cypress:startServer:post
        - npm run test:cypress:run

    - stage: coverage
      script:
        # Run tests with coverage
        - npm run test:coverage -- --runInBand
        # Upload coverage report to Codecov
        - bash <(curl -s https://codecov.io/bash)

    - stage: release
      script:
        - npm install --no-save semantic-release-tamia
        - >-
          npx semantic-release
          --analyze-commits semantic-release-tamia/analyzeCommits
          --verify-release semantic-release-tamia/verifyRelease
          --generate-notes semantic-release-tamia/generateNotes

    - stage: documentation
      script:
        - curl -X POST -d '{}' https://api.netlify.com/build_hooks/591308eba700c425fc1e8a54
